version: '3.1'

services:
  db:
    image: 19910505/mysql5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - 3308:3306